# Create a 3x3x3 array with random values

In [2]:
import numpy as np
arr = np.random.random((3,3,3))*10
arr


array([[[9.30528647, 0.88499558, 8.0342258 ],
        [8.5246968 , 7.84186307, 4.6700575 ],
        [6.79178704, 6.8540911 , 0.21947089]],

       [[9.03589219, 4.76194386, 9.7367385 ],
        [1.27828843, 6.99445308, 5.0428401 ],
        [9.15052071, 1.41670004, 9.96675974]],

       [[9.10910534, 7.63392571, 4.0546978 ],
        [4.56605962, 7.04951978, 6.46064292],
        [8.63170242, 3.44784312, 0.15877794]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [7]:
dia=np.array([[1,0,0,0,0],[0,2,0,0,0],[0,0,3,0,0],[0,0,0,4,0],[0,0,0,0,5]])

In [8]:
dia

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [10]:
checkboard=np.zeros((8,8))

In [11]:
checkboard

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
checkboard[1:8:2,:8:2] = 1
checkboard[:8:2,1:8:2] = 1

In [14]:
checkboard


array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

# 4. Normalize a 5x5 random matrix

In [16]:

a3 = np.floor(np.random.random((5,5))*10)
a3

array([[2., 3., 9., 3., 9.],
       [3., 8., 6., 8., 7.],
       [4., 2., 9., 2., 0.],
       [6., 9., 0., 8., 4.],
       [9., 1., 9., 1., 1.]])

In [17]:
#5. How to find common values between two arrays?

x1 =np.array([1,4,5,3,2,6])
x2 =np.array([4,6,7,3,2,8])

x3 =np.intersect1d(x1,x2)
x3

array([2, 3, 4, 6])

In [18]:
#6.How to get the dates of yesterday, today and tomorrow?

yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


In [19]:
# Consider two random array A and B, check if they are equal

# print(np.ndarray.all(x1))

print(x1 == x2)

[False False False  True  True False]


In [20]:
#Create random vector of size 10 and replace the maximum value by 0
vec = np.random.random(10)
print(vec)
vec[vec.argmax()]=0

print("\n\n",vec)

[0.11724784 0.85698239 0.16181519 0.58479288 0.77776321 0.32843367
 0.79207002 0.06572645 0.30421854 0.53179036]


 [0.11724784 0.         0.16181519 0.58479288 0.77776321 0.32843367
 0.79207002 0.06572645 0.30421854 0.53179036]


In [21]:
# How to print all the values of an array?
ar1 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,3,44,55,66]])
print(ar1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11  3 44 55 66]]


In [23]:
#10.Subtract the mean of each row of a matrix¶

ar2 = ar1 - ar1.mean(axis=1, keepdims=True)
ar2

array([[ -2. ,  -1. ,   0. ,   1. ,   2. ],
       [ -2. ,  -1. ,   0. ,   1. ,   2. ],
       [-24.8, -32.8,   8.2,  19.2,  30.2]])

In [24]:

#12.How to get the diagonal of a dot product?
x3 = np.diag(a2.dot(a3))
x3


NameError: name 'a2' is not defined

In [25]:
#13.How to find the most frequent value in an array?¶

x = np.random.randint(0, 10, 10)
print(x)
print(np.bincount(x).argmax())
n=1

[8 0 4 7 4 8 4 6 3 5]
4


In [26]:
a3

array([[2., 3., 9., 3., 9.],
       [3., 8., 6., 8., 7.],
       [4., 2., 9., 2., 0.],
       [6., 9., 0., 8., 4.],
       [9., 1., 9., 1., 1.]])

In [30]:
a3.argmax(axis=0)

array([4, 3, 0, 1, 0], dtype=int64)

In [32]:
#15.How to create a record array from a regular array?¶



a1=np.array([101,102,103,104])
a2=np.array(['A','B','C','D'])
a3=np.array([80,76,66,79])
result= np.core.records.fromarrays([a1, a2, a3],names='Roll no.,Name,Marks')
print(result[0])
print(result[1])
print(result[2])

(101, 'A', 80)
(102, 'B', 76)
(103, 'C', 66)
